// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Result struct {
	ID        int32
	UserID    int32
	PageUrl   string
	LinkUrl   string
	Status    string
	CheckedAt time.Time
}

type Session struct {
	ID           int32
	UserID       int32
	SessionToken string
	ExpiresAt    time.Time
	CreatedAt    time.Time
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt time.Time
}
